server:
  port: 9090
  error:
    whitelabel:
      enabled: false

spring:
  output.ansi.enabled: always
  devtools:
    restart:
      enabled: true

logging:
  level:
    root: error
    com.joje.postmelon: debug

postmelon:
  uri:
    search: https://www.melon.com/search/total/index.htm?q=
    detail: https://www.melon.com/song/detail.htm?songId=