server:
  port: 9090
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: dev
  output.ansi.enabled: always
  devtools:
    restart:
      enabled: true

logging:
  level:
    root: error
    com.joje.postmelon: info

postmelon:
  uri:
    search: https://www.melon.com/search/total/index.htm?q=
    detail: https://www.melon.com/song/detail.htm?songId=


---
  # Local
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: error
    com.joje.postmelon: debug
---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: error
    com.joje.postmelon: info